sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - demo

jobs:
  include:
    - stage: Mail-Seneca-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mail_seneca_flowz:$TRAVIS_BRANCH ./vmailSeneca/
      - docker images
      - docker tag mail_seneca_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mail_seneca_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mail_seneca_flowz:$TRAVIS_BRANCH
    - stage: Mail-Email-Services-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mail_email_services_flowz:$TRAVIS_BRANCH ./vmailServices/email-services/
      - docker images
      - docker tag mail_email_services_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mail_email_services_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mail_email_services_flowz:$TRAVIS_BRANCH
    - stage: Mail-Backend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mail_backend_flowz:$TRAVIS_BRANCH ./vmailServer/
      - docker images
      - docker tag mail_backend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mail_backend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mail_backend_flowz:$TRAVIS_BRANCH
    - stage: Mail-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mail_frontend_flowz:$TRAVIS_BRANCH ./vmailClient/
      - docker images
      - docker tag mail_frontend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mail_frontend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mail_frontend_flowz:$TRAVIS_BRANCH
    - stage: Upgrade Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./upgrade_demo.sh;
         else
            bash ./upgrade.sh;
         fi'
    - stage: Finish Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./finish_demo.sh;
         else
            bash ./finish.sh;
         fi'

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - kavib@officebrain.com
      - chirag@officebrain.com
    on_success: always
    on_failure: always         
